//! 小米配置 — 默认按键别名和虚拟键码表

/// 小米遥控器默认按键别名
pub fn default_button_aliases() -> Vec<(&'static str, &'static str)> {
    vec![
        ("power", "电源"),
        ("volume_up", "音量+"),
        ("volume_down", "音量-"),
        ("dpad_up", "上"),
        ("dpad_down", "下"),
        ("dpad_left", "左"),
        ("dpad_right", "右"),
        ("ok", "确定"),
        ("back", "返回"),
        ("home", "主页"),
        ("menu", "菜单"),
        ("voice", "语音"),
        ("mute", "静音"),
    ]
}

/// 虚拟键码 → 名称映射
pub fn vk_code_to_name(vk: u16) -> String {
    match vk {
        0x08 => "Backspace".to_string(),
        0x09 => "Tab".to_string(),
        0x0D => "Enter".to_string(),
        0x10 => "Shift".to_string(),
        0x11 => "Ctrl".to_string(),
        0x12 => "Alt".to_string(),
        0x13 => "Pause".to_string(),
        0x14 => "CapsLock".to_string(),
        0x1B => "Escape".to_string(),
        0x20 => "Space".to_string(),
        0x21 => "PageUp".to_string(),
        0x22 => "PageDown".to_string(),
        0x23 => "End".to_string(),
        0x24 => "Home".to_string(),
        0x25 => "Left".to_string(),
        0x26 => "Up".to_string(),
        0x27 => "Right".to_string(),
        0x28 => "Down".to_string(),
        0x2C => "PrintScreen".to_string(),
        0x2D => "Insert".to_string(),
        0x2E => "Delete".to_string(),
        0x30 => "0".to_string(),
        0x31 => "1".to_string(),
        0x32 => "2".to_string(),
        0x33 => "3".to_string(),
        0x34 => "4".to_string(),
        0x35 => "5".to_string(),
        0x36 => "6".to_string(),
        0x37 => "7".to_string(),
        0x38 => "8".to_string(),
        0x39 => "9".to_string(),
        0x41 => "A".to_string(),
        0x42 => "B".to_string(),
        0x43 => "C".to_string(),
        0x44 => "D".to_string(),
        0x45 => "E".to_string(),
        0x46 => "F".to_string(),
        0x47 => "G".to_string(),
        0x48 => "H".to_string(),
        0x49 => "I".to_string(),
        0x4A => "J".to_string(),
        0x4B => "K".to_string(),
        0x4C => "L".to_string(),
        0x4D => "M".to_string(),
        0x4E => "N".to_string(),
        0x4F => "O".to_string(),
        0x50 => "P".to_string(),
        0x51 => "Q".to_string(),
        0x52 => "R".to_string(),
        0x53 => "S".to_string(),
        0x54 => "T".to_string(),
        0x55 => "U".to_string(),
        0x56 => "V".to_string(),
        0x57 => "W".to_string(),
        0x58 => "X".to_string(),
        0x59 => "Y".to_string(),
        0x5A => "Z".to_string(),
        0x5B => "LWin".to_string(),
        0x5C => "RWin".to_string(),
        0x5D => "Apps".to_string(),
        0x70 => "F1".to_string(),
        0x71 => "F2".to_string(),
        0x72 => "F3".to_string(),
        0x73 => "F4".to_string(),
        0x74 => "F5".to_string(),
        0x75 => "F6".to_string(),
        0x76 => "F7".to_string(),
        0x77 => "F8".to_string(),
        0x78 => "F9".to_string(),
        0x79 => "F10".to_string(),
        0x7A => "F11".to_string(),
        0x7B => "F12".to_string(),
        0xA0 => "LShift".to_string(),
        0xA1 => "RShift".to_string(),
        0xA2 => "LCtrl".to_string(),
        0xA3 => "RCtrl".to_string(),
        0xA4 => "LAlt".to_string(),
        0xA5 => "RAlt".to_string(),
        0xAD => "VolumeMute".to_string(),
        0xAE => "VolumeDown".to_string(),
        0xAF => "VolumeUp".to_string(),
        0xB0 => "MediaNext".to_string(),
        0xB1 => "MediaPrev".to_string(),
        0xB2 => "MediaStop".to_string(),
        0xB3 => "MediaPlayPause".to_string(),
        0xFC => "VK_NONAME(0xFC)".to_string(),
        _ => format!("VK_{:#04X}", vk),
    }
}

/// 蓝牙地址规范化：去除分隔符，转大写
pub fn normalize_bluetooth_address(addr: &str) -> String {
    let cleaned: String = addr
        .chars()
        .filter(|c| c.is_ascii_hexdigit())
        .collect();
    cleaned.to_uppercase()
}
